---
title: "HM-KS"
author: "Kee-Young Shin"
date: "5/10/2020"
output: html_document
---

```{r}
library(msm)
library(invgamma)

# functions for posteriors
# use log to make it additive 

rho_prior = function(rho){
  prob = dtnorm(rho, mean = 0.5, sd = sqrt(1/5), lower = 0, upper = 1)
  return(log(prob))
}

sigma_prior = function(sigma){
  prob = dinvgamma(1/sigma, 0.001, 0.001)
  return(log(prob))
}

beta_prior = function(beta){
  prob = dnorm(beta, 0, 1)
  return(sum(log(prob)))
}

loglike = function(Y, X, betas, rhos, sigma){
  resp = as.matrix(Y)
  X = data.matrix(X)
  coef = c(betas, rhos)
  mean = X %*% coef
  # constants removed since they will be canceled out anyway 
  loglik = (-0.5/sigma)*(resp - mean)^2
  return(sum(loglik))
}

posteriors = function(Y, X, betas, rhos, sigma) {
  loglik = loglike(Y, X, betas, rhos, sigma)
  beta_p = beta_prior(betas)
  rho_p = rho_prior(rhos)
  sigma_p = sigma_prior(sigma)
  return(rho_p + sigma_p + beta_p + loglik)
}

# create MH algorithm
mh = function(Y, X, start_b, start_r, start_s, 
              window_b, window_r, window_s, n){
  p = length(start_b)
  r = length(start_r)
  res_b = start_b
  res_r = start_r
  res_s = start_s
  chain = c(1, start_b, start_r, start_s)
  for (i in 2:n){
    for (j in 1:p) {
      proposed_b = res_b
      proposed_b[j] = res_b[j] + (runif(1) - 0.5)*2*window_b[j]
      numer = posteriors(Y, X, proposed_b, res_r, res_s)
      denom = posteriors(Y, X, res_b, res_r, res_s)
      if (log(runif(1)) < (numer - denom)) {
        res_b = proposed_b
      }
    }
    for (m in 1:r) {
      proposed_r = res_r
      proposed_r[m] = res_r[m] + (runif(1) - 0.5)*2*window_r
      numer = posteriors(Y, X, res_b, proposed_r, res_s)
      denom = posteriors(Y, X, res_b, res_r, res_s)
      if (log(runif(1)) < (numer - denom)) {
        res_r = proposed_r
      }
    }
    proposed_s = 1/rinvgamma(1, .001*window_s, .001*window_s)
    numer = posteriors(Y, X, res_b, res_r, proposed_s)
    denom = posteriors(Y, X, res_b, res_r, res_s)
    if (log(runif(1)) < (numer - denom)) {
      res_s = proposed_s
    }
    chain = rbind(chain, c(i, res_b, res_r, res_s))
  }
  return(chain)
}
```

```{r}
resp = dt %>% 
  select(Wind.kt)
data.frame(dt)
summary(dt)

# select 80% of hurricanes as training set
hurricanes_id = as.character(unique(dt$ID))
train_ind = sample(1:length(hurricanes_id), 
                   size = floor(.8*length(hurricanes_id)),
                   replace = FALSE)
train_hurr = hurricanes_id[train_ind]

# create datasets for response and predictors for 
# training and test sets
train_X = dt %>%
  filter(ID %in% train_hurr) %>%
  mutate(intercept = 1,
         diff_lat = ifelse(is.na(diff_lat), 0, diff_lat),
         diff_long = ifelse(is.na(diff_long), 0, diff_long),
         diff_spd = ifelse(is.na(diff_spd), 0, diff_spd)) %>%
  group_by(ID) %>% 
  mutate(wind_t = lag(Wind.kt, default = first(Wind.kt))) %>% 
  select(intercept, day, Season, Nature, 
         diff_lat, diff_long, diff_spd, wind_t)

train_Y = dt %>%
  filter(ID %in% train_hurr) %>%
  select(Wind.kt)

test_X = dt %>%
  filter(!(ID %in% train_hurr)) %>%
  mutate(intercept = 1) %>%
  select(intercept, day_of_yr, year, Nature, 
         diff_lat, diff_long, diff_spd, Wind.kt)

test_Y = dt %>%
  filter(!(ID %in% train_hurr)) %>%
  select(Wind.kt)

```

```{r}
set.seed(24)
chains = mh(train_Y, train_X, start_b = rep(0,7), 
            start_r = 0.6, start_s = 10, window_b = rep(1,7),
            window_r = 0.02, window_s = 150, n = 1000)

chains[1000,]
```

