---
title: "Prediction Plots: Test Set"
author: "Melanie Mayer"
date: "5/12/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(corrplot)
library(ModelMetrics)
```

Read in data:

```{r}
preds <- read.csv("./preds2.csv") %>% 
  group_by(ID) %>% 
  mutate(t = 1,
         t = (cumsum(t) - 1) * 6) %>% 
  rename(resids = Wind.t6.1)

length(levels(preds$ID))
#Test set:71 hurricanes

#Pick hurricanes with most data points
preds %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) 

```


Create plot:

```{r}
preds %>% 
  filter(ID == "IVAN.2004") %>% 
  gather(key = type, value = wind.speed, c("preds", "Wind.t6")) %>% 
  ggplot(aes(x = t, y = wind.speed, group = type, colour = type)) + 
  geom_smooth(alpha = 0.35, se = F, size = 0.65) +
  geom_point(alpha = 0.5) + 
      labs(title = "Hurricane Ivan (2004)",
           x = "Time",
         y = "Wind Speed",
         color = "") + 
    scale_color_manual(labels = c("Predicted", "Obseved") , values = c("purple", "red")) + 
  theme_bw()


preds %>% 
  filter(ID == "IVAN.2004") %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2) + 
  labs(title="Felix 1995", x="Residuals", y="Count") + 
  theme_bw()


preds %>% 
  filter(ID == "KYLE.2002") %>% 
  gather(key = type, value = wind.speed, c("preds", "Wind.t6")) %>% 
  ggplot(aes(x = t, y = wind.speed, group = type, colour = type)) + 
  geom_smooth(alpha = 0.5, se = F) +
  geom_point(alpha = 0.5) + 
      labs(title = "Hurricane Dennis (1999)",
           x = "Time",
         y = "Wind Speed",
         color = "") + 
    scale_color_manual(labels = c("Predicted", "Obseved") , values = c("lightblue", "red")) + 
  theme_bw()


preds %>% 
  filter(ID == "KYLE.2002") %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2) + 
  labs(title="Felix 1995", x="Residuals", y="Count") + 
  theme_bw()

preds %>% 
  filter(ID == "ERIKA.1997") %>% 
  gather(key = type, value = wind.speed, c("preds", "Wind.t6")) %>% 
  ggplot(aes(x = t, y = wind.speed, group = type, colour = type)) + 
  geom_smooth(alpha = 0.35, se = F, size = 0.65) +
  geom_point(alpha = 0.5) + 
      labs(title = "Hurricane Erika (1997)",
           x = "Time",
         y = "Wind Speed",
         color = "") + 
  scale_color_manual(labels = c("Predicted", "Obseved") , values = c("purple", "red")) + 
  theme_bw()

preds %>% 
  filter(ID == "ERIKA.1997") %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2) + 
  labs(title=" ", x="Residuals", y="Count") + 
  theme_bw()

preds %>% 
  filter(ID == "LUIS.1995") %>% 
  gather(key = type, value = wind.speed, c("preds", "Wind.t6")) %>% 
  ggplot(aes(x = t, y = wind.speed, group = type, colour = type)) + 
  geom_smooth(alpha = 0.35, se = F, size = 0.65) +
  geom_point(alpha = 0.5) + 
      labs(title = "Hurricane Luis (1995)",
           x = "Time",
         y = "Wind Speed",
         color = "") + 
    scale_color_manual(labels = c("Predicted", "Obseved") , values = c("purple", "red")) + 
  theme_bw()

preds %>% 
  filter(ID == "LUIS.1995") %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2) + 
  labs(title=" ", x="Residuals", y="Count") + 
  theme_bw()

preds %>% 
  filter(ID == "HUGO.1989") %>% 
  gather(key = type, value = wind.speed, c("preds", "Wind.t6")) %>% 
  ggplot(aes(x = t, y = wind.speed, group = type, colour = type)) + 
  geom_smooth(alpha = 0.5, se = F) +
  geom_point(alpha = 0.5) + 
      labs(title = "Hurricane Hugo (1989)",
           x = "Time",
         y = "Wind Speed",
         color = "") + 
    scale_color_manual(labels = c("Predicted", "Obseved") , values = c("lightblue", "red"))

preds %>% 
  filter(ID == "HUGO.1989") %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2) + 
  labs(title="Irene 2005", x="Residuals", y="Count") + 
  theme_bw()


preds %>% 
  filter(ID == "ARLENE.1993") %>% 
  gather(key = type, value = wind.speed, c("preds", "Wind.t6")) %>% 
  ggplot(aes(x = t, y = wind.speed, group = type, colour = type)) + 
  geom_smooth(alpha = 0.35, se = F, size = 0.65) +
  geom_point(alpha = 0.5) + 
      labs(title = "Hurricane Arlene (1993)",
           x = "Time",
         y = "Wind Speed",
         color = "") + 
  scale_color_manual(labels = c("Predicted", "Obseved") , values = c("purple", "red")) + 
  theme_bw()

preds %>% 
  filter(ID == "ARLENE.1993") %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2) + 
  labs(title="", x="Residuals", y="Count") + 
  theme_bw()


preds %>% 
  filter(ID == "NOEL.1995") %>% 
  gather(key = type, value = wind.speed, c("preds", "Wind.t6")) %>% 
  ggplot(aes(x = t, y = wind.speed, group = type, colour = type)) + 
  geom_smooth(alpha = 0.35, se = F, size = 0.65) +
  geom_point(alpha = 0.5) + 
      labs(title = "Hurricane Noel (1995)",
           x = "Time",
         y = "Wind Speed",
         color = "") + 
  scale_color_manual(labels = c("Predicted", "Obseved") , values = c("purple", "red")) + 
  theme_bw()

preds %>% 
  filter(ID == "NOEL.1995") %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2) + 
  labs(title="", x="Residuals", y="Count") + 
  theme_bw()


preds %>% 
  filter(ID == "EMILY.1993") %>% 
  gather(key = type, value = wind.speed, c("preds", "Wind.t6")) %>% 
  ggplot(aes(x = t, y = wind.speed, group = type, colour = type)) + 
  geom_smooth(alpha = 0.35, se = F, size = 0.65) +
  geom_point(alpha = 0.5) + 
      labs(title = "Hurricane Emily (1993)",
           x = "Time",
         y = "Wind Speed",
         color = "") + 
  scale_color_manual(labels = c("Predicted", "Obseved") , values = c("purple", "red")) + 
  theme_bw()

preds %>% 
  filter(ID == "EMILY.1993") %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2) + 
  labs(title="", x="Residuals", y="Count") + 
  theme_bw()

preds %>% 
  filter(ID == "EDOUARD.1990") %>% 
  gather(key = type, value = wind.speed, c("preds", "Wind.t6")) %>% 
  ggplot(aes(x = t, y = wind.speed, group = type, colour = type)) + 
  geom_smooth(alpha = 0.35, se = F, size = 0.65) +
  geom_point(alpha = 0.5) + 
      labs(title = "Hurricane Edouard (1990)",
           x = "Time",
         y = "Wind Speed",
         color = "") + 
  scale_color_manual(labels = c("Predicted", "Obseved") , values = c("purple", "red")) + 
  theme_bw()

preds %>% 
  filter(ID == "EDOUARD.1990") %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2) + 
  labs(title="", x="Residuals", y="Count") + 
  theme_bw()

preds %>% 
  filter(ID == "HORTENSE.1996") %>% 
  gather(key = type, value = wind.speed, c("preds", "Wind.t6")) %>% 
  ggplot(aes(x = t, y = wind.speed, group = type, colour = type)) + 
  geom_smooth(alpha = 0.35, se = F, size = 0.65) +
  geom_point(alpha = 0.5) + 
      labs(title = "Hurricane Hortense (1996)",
           x = "Time",
         y = "Wind Speed",
         color = "") + 
  scale_color_manual(labels = c("Predicted", "Obseved") , values = c("purple", "red")) + 
  theme_bw()

preds %>% 
  filter(ID == "HORTENSE.1996") %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2) + 
  labs(title="", x="Residuals", y="Count") + 
  theme_bw()

```

MSE:

```{r}
preds %>% 
  ggplot(aes(x = resids)) + 
  geom_histogram(col="blue", 
                 fill="blue", 
                 alpha = .2,
                 bins = 50) + 
  labs(title="", x="Residuals", y="Count") + 
  theme_bw()


resids.no.na <- preds %>% filter(!is.na(preds))
mse(resids.no.na$Wind.t6, resids.no.na$preds)

```


