---
title: "Project 4 Code - Hurricane Predictions"
author: "Margaret Gacheru, Melanie Mayer, Kee-Young Shin, Adina Zhang"
date: "5/8/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(lubridate)
```


Data Cleaning:

```{r}
dt = read.csv("./hurrican356.csv") %>% 
  arrange(-desc(time)) %>% 
  separate(time, into = c("date", "time"), sep = " ") %>% 
  mutate(time = str_replace(time, "\\)", ""),
         date = str_replace(date, "\\(", ""),
         day_of_yr = ymd(date) - ymd(paste0(year(date), "-01-01")),
         day_of_yr = as.numeric(day_of_yr, units = "days")) %>% 
  separate(time, into = c("time", "temp", "temp2"), sep = ":") %>% 
  mutate(time = as.numeric(time)) %>% 
  select(-c(X, date, temp, temp2)) %>% 
  group_by(ID) %>% 
  mutate(t = 1,
         t = (cumsum(t) - 1) * 6,
         diff_lat = Latitude - lag(Latitude, default = NA),
         diff_long = Longitude - lag(Longitude, default = NA),
         diff_spd = Wind.kt - lag(Wind.kt, default = NA),
         Wind.t6 = lead(Wind.kt),
         Nature = factor(Nature, 
                         levels = c("NR", "DS", "ET", "SS", "TS")),
         Nature = as.numeric(Nature)) %>% 
  rename(year = Season) %>% 
  ungroup()

```

Split Data:

```{r}
# Split data into training and test sets
trainIndex = createDataPartition(dt$Wind.kt, p = 0.8, list = F)
dt_train = dt[trainIndex,]
dt_test = dt[-trainIndex,]
```

